import json

notebook_path = r"c:\Users\vilas\Documents\CIR\basics inverse kinematics\connectingjupyter\one leg test.ipynb"

new_source = [
    "# --- TRAJECTORY FUNCTION ---\n",
    "def generate_line_trajectory_multi_leg(start_poses, end_poses, steps):\n",
    "    \"\"\"\n",
    "    Generates trajectories for all 6 legs simultaneously.\n",
    "    start_poses: list of 6 (x,y,z) tuples\n",
    "    end_poses: list of 6 (x,y,z) tuples\n",
    "    Returns: List of lists [[(x,y,z)_leg0, ...], ...] for each step\n",
    "    \"\"\"\n",
    "    all_trajectories = []\n",
    "    for i in range(6):\n",
    "        traj = generate_line_trajectory(start_poses[i], end_poses[i], steps)\n",
    "        all_trajectories.append(traj)\n",
    "    \n",
    "    # Transpose to get list of steps where each step has 6 coords\n",
    "    # zip(*all_trajectories) -> iterator of tuples\n",
    "    return list(zip(*all_trajectories))\n",
    "\n",
    "# --- GAIT SEQUENCE DEFINITION ---\n",
    "# P1: Home / All Down\n",
    "POSE_1 = [\n",
    "    (270.50, 0.00, -122.00),   # Leg 0\n",
    "    (60.25, 190.96, -122.00),  # Leg 1\n",
    "    (-160.25, 190.96, -122.00),# Leg 2\n",
    "    (-170.50, 0.00, -122.00),  # Leg 3\n",
    "    (-160.25, -190.96, -122.00),# Leg 4\n",
    "    (60.25, -190.96, -122.00)  # Leg 5\n",
    "]\n",
    "\n",
    "# P2: Lift A (0, 2, 4)\n",
    "POSE_2 = [\n",
    "    (270.50, 0.00, -82.00),    # Leg 0 (Lift)\n",
    "    (60.25, 190.96, -122.00),  # Leg 1\n",
    "    (-160.25, 190.96, -82.00), # Leg 2 (Lift)\n",
    "    (-170.50, 0.00, -122.00),  # Leg 3\n",
    "    (-160.25, -190.96, -82.00),# Leg 4 (Lift)\n",
    "    (60.25, -190.96, -122.00)  # Leg 5\n",
    "]\n",
    "\n",
    "# P3: Swing A Fwd, B Bwd\n",
    "POSE_3 = [\n",
    "    (170.50, 0.00, -82.00),    # Leg 0 (Swing Fwd)\n",
    "    (160.25, 190.96, -122.00), # Leg 1 (Push Bwd)\n",
    "    (-60.25, 190.96, -82.00),  # Leg 2 (Swing Fwd)\n",
    "    (-270.50, 0.00, -122.00),  # Leg 3 (Push Bwd)\n",
    "    (-60.25, -190.96, -82.00), # Leg 4 (Swing Fwd)\n",
    "    (160.25, -190.96, -122.00) # Leg 5 (Push Bwd)\n",
    "]\n",
    "\n",
    "# P4: Lower A (Plant)\n",
    "POSE_4 = [\n",
    "    (170.50, 0.00, -122.00),   # Leg 0 (Down)\n",
    "    (160.25, 190.96, -122.00), # Leg 1\n",
    "    (-60.25, 190.96, -122.00), # Leg 2 (Down)\n",
    "    (-270.50, 0.00, -122.00),  # Leg 3\n",
    "    (-60.25, -190.96, -122.00),# Leg 4 (Down)\n",
    "    (160.25, -190.96, -122.00) # Leg 5\n",
    "]\n",
    "\n",
    "# P5: Lift B (1, 3, 5)\n",
    "POSE_5 = [\n",
    "    (170.50, 0.00, -122.00),   # Leg 0\n",
    "    (160.25, 190.96, -82.00),  # Leg 1 (Lift)\n",
    "    (-60.25, 190.96, -122.00), # Leg 2\n",
    "    (-270.50, 0.00, -82.00),   # Leg 3 (Lift)\n",
    "    (-60.25, -190.96, -122.00),# Leg 4\n",
    "    (160.25, -190.96, -82.00)  # Leg 5 (Lift)\n",
    "]\n",
    "\n",
    "# P6: Swing B Fwd, A Bwd\n",
    "POSE_6 = [\n",
    "    (270.50, 0.00, -122.00),   # Leg 0 (Push Bwd)\n",
    "    (60.25, 190.96, -82.00),   # Leg 1 (Swing Fwd)\n",
    "    (-160.25, 190.96, -122.00),# Leg 2 (Push Bwd)\n",
    "    (-170.50, 0.00, -82.00),   # Leg 3 (Swing Fwd)\n",
    "    (-160.25, -190.96, -122.00),# Leg 4 (Push Bwd)\n",
    "    (60.25, -190.96, -82.00)   # Leg 5 (Swing Fwd)\n",
    "]\n",
    "\n",
    "# Sequence: P1 -> P2 -> P3 -> P4 -> P5 -> P6 -> P1\n",
    "GAIT_SEQUENCE = [POSE_1, POSE_2, POSE_3, POSE_4, POSE_5, POSE_6, POSE_1]\n",
    "STEPS_PER_MOVE = 20\n",
    "\n",
    "# --- EXECUTION LOOP ---\n",
    "# Connect to Serial (Optional)\n",
    "ser = None\n",
    "try:\n",
    "    ser = serial.Serial(PORT, BAUD, timeout=1)\n",
    "    time.sleep(2)\n",
    "    print(f\"Connected to {PORT}\")\n",
    "except:\n",
    "    print(\"Serial not connected. Running simulation only.\")\n",
    "\n",
    "# Setup Plot\n",
    "fig = plt.figure(figsize=(10, 8))\n",
    "ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "def update_plot(leg_coords):\n",
    "    ax.clear()\n",
    "    ax.set_xlim(-400, 400)\n",
    "    ax.set_ylim(-400, 400)\n",
    "    ax.set_zlim(-200, 200)\n",
    "    ax.set_xlabel('X')\n",
    "    ax.set_ylabel('Y')\n",
    "    ax.set_zlabel('Z')\n",
    "    \n",
    "    # Body\n",
    "    hx, hy, hz = zip(*hip_points)\n",
    "    ax.plot(hx, hy, hz, 'k-', linewidth=2)\n",
    "    \n",
    "    # Legs\n",
    "    for i in range(6):\n",
    "        tx, ty, tz = leg_coords[i]\n",
    "        pts = get_leg_points(i, tx, ty, tz)\n",
    "        if pts:\n",
    "            px, py, pz = zip(*pts)\n",
    "            ax.plot(px, py, pz, '-o', linewidth=2)\n",
    "\n",
    "print(\"Starting Gait Sequence...\")\n",
    "\n",
    "# Loop through sequence transitions\n",
    "for seq_idx in range(len(GAIT_SEQUENCE) - 1):\n",
    "    start_p = GAIT_SEQUENCE[seq_idx]\n",
    "    end_p = GAIT_SEQUENCE[seq_idx + 1]\n",
    "    \n",
    "    print(f\"Move {seq_idx+1}: Pose {seq_idx} -> Pose {seq_idx+1}\")\n",
    "    \n",
    "    # Generate frame-by-frame points for all legs\n",
    "    frames = generate_line_trajectory_multi_leg(start_p, end_p, STEPS_PER_MOVE)\n",
    "    \n",
    "    for frame_coords in frames:\n",
    "        # frame_coords is a tuple of 6 (x,y,z) tuples\n",
    "        \n",
    "        # 1. Plot\n",
    "        update_plot(frame_coords)\n",
    "        plt.draw()\n",
    "        plt.pause(0.001)\n",
    "        \n",
    "        # 2. Calculate Servos & Send\n",
    "        command_us = []\n",
    "        for i in range(6):\n",
    "            tx, ty, tz = frame_coords[i]\n",
    "            u1, u2, u3 = get_servo_us_for_leg(i, tx, ty, tz)\n",
    "            command_us.extend([u1, u2, u3])\n",
    "            \n",
    "        line = \",\".join(str(v) for v in command_us) + \"\\n\"\n",
    "        if ser:\n",
    "            ser.write(line.encode(\"ascii\"))\n",
    "        \n",
    "        # Small delay for servo speed limit\n",
    "        time.sleep(0.02)\n",
    "\n",
    "if ser:\n",
    "    ser.close()\n",
    "print(\"Gait Cycle Complete.\")\n"
]

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# Find the cell to replace (trajectory_test)
found = False
for cell in nb['cells']:
    if cell.get('id') == 'trajectory_test':
        cell['source'] = new_source
        # Clear outputs to avoid large file size
        cell['outputs'] = []
        cell['execution_count'] = None
        found = True
        break

if not found:
    print("Cell 'trajectory_test' not found, appending new cell")
    new_cell = {
        "cell_type": "code",
        "execution_count": None,
        "id": "gait_sequence",
        "metadata": {},
        "outputs": [],
        "source": new_source
    }
    nb['cells'].append(new_cell)

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=4)

print("Notebook updated successfully.")
